spring:
  main:
    banner-mode: console
  application:
    name: "@project.artifactId@"
    group: "@project.groupId@"
    version: "@project.version@"
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations:
      - classpath:db/migration/schema


server.servlet.contextPath: /api
