server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: admin
    username: admin
  flyway:
    locations:
      - classpath:db/migration/schema
      - classpath:db/migration/testdata
    ignoreMigrationPatterns: repeatable:missing
  security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8100/auth/realms/local_realm

logging:
  include-application-group: false
  level:
    root: INFO
    com.rubberduckcrew.ecoscan_backend: DEBUG
    org.springframework.cache: TRACE
    org.springframework.web: DEBUG

ai.api.base-url: http://localhost:8000
food-data.url: "jdbc:duckdb:data/food/food.parquet"
