research_alternatives_task:
  description: >
    Analyze the provided product ({product}) and its EAN ({ean}).
    Use the DuckDuckGo Search tool, but search ONLY for grocery products, 
    food alternatives, or competitive brands. 
    Your search query MUST look exactly like this: '[Product Name] alternatives' or '[Product Name] competitors'.
    Do not search for random text.
    expected_output: >
      A structured list containing the product names and EAN numbers of all found alternative products.
    agent: alternatives_researcher

find_coordinates_task:
  description: >
    Take the alternative products discovered in the previous task (research_alternatives_task). 
    For each alternative product, use the search tools to look up for one physical store or supermarket, that sells the product,
    within a 5 km radius of the user's location ({user_coordinates}). 
    Find the exact geographic latitude and longitude coordinates for each alternative product.
  expected_output: >
    A list of each ean number with their latitude and longitude of the place.
  agent: coordinates_researcher