description_task:
  description: >
    Generiere eine deutsche Ein-Satz-Beschreibung des Produkts: {productName} mit den Kategorien:
    {productCategories}. Die Beschreibung sollte prägnant, informativ und ansprechend sein, den 
    Kern des Produkts erfassen und genau einen Satz lang sein. Erlaubt sind nur ASCII-Zeichen, 
    also ohne sonderzeichen wie umlaute oder andere nicht ascii Zeichen.
  expected_output: >
    Ein valides JSON-Objekt mit genau einem Feld:
    {
      "description": "<hier die Ein-Satz-Beschreibung>"
    }
  agent: description_generator

analysis_task:
  description: >
    Analyze the product: {productName} with the categories: {productCategories}
    and product ID: {productId}.
    Gather all available data about the product focusing on: its identifying features, ecological 
    impact, sustainability aspects amd any other relevant information that can be found.
  expected_output: >
    A valid JSON object with exactly one field:
    {
      "data": "<structured information about the product>"
    }
  context: [description_task]
  agent: product_analyzer