research_alternatives_task:
  description: >
    Analyze the provided product category ({categories}).
    Use the "Search by category tool" tool with this format:
    {{"category": "your_category_here"}} to search our internal
    product database for alternative products in the same or a closely
    related category. Use the "Search products by category" tool ONCE with it.
    Use ONLY the EAN numbers returned by the tool, maximum 10.
  expected_output: >
    A list of alternative product EAN numbers
  agent: alternatives_researcher
