name: Test, Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, labeled, synchronize]

jobs:
  app:
    uses: RubberDuckCrew/expo-workflow/.github/workflows/workflow-build.yml@4c81c7960ebc83714afa8c11c343ef896a93cc14 # v1.0.0

    permissions:
      contents: write
      pull-requests: write

    with:
      app-name: 'EcoScan'
      working-directory: 'ecoscan_app'
      java-version: '21'
      gradle-version: '9.0.0'
      node-version: '24'

  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 25
          distribution: "temurin"
          cache: "maven"
          cache-dependency-path: "./ecoscan_backend/pom.xml"

      - name: Build with Maven
        run: mvn --update-snapshots -f ./ecoscan_backend/pom.xml install

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: backend-target
          path: "ecoscan_backend/target"
