name: Test, Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, labeled, synchronize]

jobs:
  app:
    uses: RubberDuckCrew/expo-workflow/.github/workflows/workflow-build.yml@4c81c7960ebc83714afa8c11c343ef896a93cc14 # v1.0.0

    permissions:
      contents: write
      pull-requests: write

    with:
      app-name: 'EcoScan'
      working-directory: 'ecoscan_app'
      java-version: '21'
      gradle-version: '9.0.0'
      node-version: '24'
